### ISSUE TITLE
Can't resolve 'fs' in '/path/to/project/node_modules/yaml-to-json-converter'

### ISSUE THREAD

**Issue by dooleydiligent** [satmaramani/yaml-to-json-converter#1]
I try:

```
const readYamlContents = require("yaml-to-json-converter");
```
and receive the error "Can't resolve 'fs' in .../yaml-to-json-converter'.

The error line is: ./node_modules/yaml-to-json-converter/index.js:1:11-24 

I'm using Angular so the fix is in tsconfig.app.json:

do 
```
npm install fs-web
```
Then add this to "compilerOptions"
```
"paths": {
      "fs": ["./node_modules/fs-web"]
    }
```
Now it works.  Thanks for your work!

**Comment by satmaramani** [comment]
Thanks for the solution

**Comment by satmaramani** [comment]
Dear @dooleydiligent 
I have also tried to initiate a fresh project and tried to get this working as a user / client

I am not able to reproduce this issue 

Which OS you are using ?

and this issue is not reported by any other user until now.

Thanks a lot for taking care of this and for providing solution 

Your Friend 

Sam

**Comment by dooleydiligent** [comment]
> Dear @dooleydiligent I have also tried to initiate a fresh project and tried to get this working as a user / client
> 
> I am not able to reproduce this issue
> 
> Which OS you are using ?
> 
> and this issue is not reported by any other user until now.
> 
> Thanks a lot for taking care of this and for providing solution
> 
> Your Friend
> 
> Sam

Hello.  I am using Angular 15 on linux.  Here is the relevant dependencies section from package.json.  I hope it helps.
```
  "dependencies": {
    "@angular/animations": "^15.0.0",
    "@angular/common": "^15.0.0",
    "@angular/compiler": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "^15.0.0",
    "@angular/platform-browser": "^15.0.0",
    "@angular/platform-browser-dynamic": "^15.0.0",
    "@angular/router": "^15.0.0",
    "@json-editor/json-editor": "^2.10.1",
    "@popperjs/core": "^2.11.6",
    "bootstrap": "^5.2.2",
    "js-yaml": "^4.1.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.0",
    "@angular/cli": "^15.2.9",
    "@angular/compiler-cli": "^15.0.0",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.2"
  }
```

I should note that I have since switched over to js-yaml for other reasons.

One more note:  The condition occurred during "hot reload" using `npm start` with this script: 
```
"scripts":{
"start": "ng serve --watch --port 8080 --host 0.0.0.0 --disable-host-check=true"
}
```
